### ISSUE TITLE
NodeSelctors looking for wrong keys/values in some jobs

### ISSUE THREAD

**Issue by mattmceuen** [att-comdev/openstack-helm#119]
Commit https://github.com/att-comdev/openstack-helm/commit/6f124d51072faa350da668708f9547070f833f19 added NodeSelectors to several jobs across several components, using the value ".Vales.labels.node_selector_key".  However, some components (neutron, nova) have more granular node selection, e.g.  ".Values.labels.server.node_selector_key", and this is causing make to fail with errors like the following for me:

==> Linting neutron
[ERROR] templates/job-db-sync.yaml: unable to parse YAML
    error converting YAML to JSON: yaml: line 9: did not find expected key
[ERROR] templates/job-init.yaml: unable to parse YAML
    error converting YAML to JSON: yaml: line 9: did not find expected key
[ERROR] templates/job-post.yaml: unable to parse YAML
    error converting YAML to JSON: yaml: line 9: did not find expected key

**Comment by wilkers-steve** [comment]
Yep, I noticed this as well.  Spoke with portdirect regarding this issue on Friday.  This will need to be addressed before releasing our first tagged version this coming week.

**Comment by v1k0d3n** [comment]
This is true @mattmceuen. This is going to be cleaned up very soon, prior to a true 0.1.0 release. Going forward the project will have firm deadlines and bake-in periods for releases, and things like this will be addressed ahead of time. For our first initial release, we're going to have a working session next week and iron out each of these outstanding issues prior to official tagging. Then all docs will be updated for that tagged release, so the community will have a good starting point for an Openstack control plane (with vm guest support).

**Comment by v1k0d3n** [comment]
this has now been merged.
