### ISSUE TITLE
help: Can't login to container

### ISSUE THREAD

**Issue by Masber** [att-comdev/openstack-helm#121]
Hi,

I can't edit the /etc/resolv.conf file within the container following the instructions:

```
[root@kub1 ~]# kubectl exec kube-controller-manager-kub1.localdomain -it -n kube-system -- /bin/bash
exec: "/bin/bash": stat /bin/bash: no such file or directory
error: error stream protocol error: invalid exit code value "-1"
```

however 

```
[root@kub1 ~]# kubectl exec kube-controller-manager-kub1.localdomain -it -n kube-system -- echo $0
-bash
```

Any idea?

thank you

**Comment by v1k0d3n** [comment]
@Masber have  you been able to solve your issue? This falls outside of openstack-helm, so we may be able to address your question in the Kubernetes slack community. Would that work for you?

**Comment by v1k0d3n** [comment]
i want to give this a couple more days, but haven't heard back from @Masber on if this  is still an issue or not.

**Comment by Masber** [comment]
this has been fixed.
`kubectl exec kube-controller-manager-kub1.localdomain -it -n kube-system -- /bin/sh` is the command to run

thanks

**Comment by v1k0d3n** [comment]
great! thanks @Masber
