### ISSUE TITLE
ci: basic linting for repository

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#144]
we need some basic linting and CI gating for our repository. this will make the community more confident in the changes they are submitting, and help assist reviewers before merging code into our repository as well.

**Comment by js5175** [comment]
@nadeemanwar has started investigating. we are going to support the following:
- initially review ALL files and resolve open issues
- triggered job will review for just the changed files syntax/lint

**Comment by wilkers-steve** [comment]
Brandon, can you add me as an assignee?  I've got linting working through TravisCI, and close to having `helm install --dry-run --debug` working.  These will be the logical first steps and offer us at least some basic jobs to watch the repo.

https://travis-ci.org/wilkers-steve/openstack-helm

The current jobs I have running in TravisCI run `make` on the repo, but the next step is to break these out into logical jobs so we've got some granularity on seeing what fails.

**Comment by js5175** [comment]
@na1431 @wilkers-steve can we review and determine how Jenkins and Travis compare? I want to make sure we aren't duplicating work. And if Travis is better let's understand why:)

**Comment by js5175** [comment]
@nadeemanwar

**Comment by wilkers-steve** [comment]
@nadeemanwar @js5175 Absolutely!

**Comment by v1k0d3n** [comment]
@js5175 @nadeemanwar @wilkers-steve: for one, since the travis.yml and other CI information will be in the open (in the repo) and available to developers, the community can maintain testing for the gate. i would say this is a huge improvement for what we're able to do over an internal Jenkins build (as it's currently done today). if we were to put the Jenkins pipeline in the open under [aic-ci/ci-jenkins](https://github.com/att-comdev/aic-ci) then this isn't an issue, but that's not how things have worked out so far.

**Comment by nadeemanwar** [comment]
May be we can talk about that in the parking lot today.
