### ISSUE TITLE
ci: repo templates for issues, automatic labeling, etc.

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#145]
We need to define contribution guidelines, create issue templates and automatically label based on key words, etc.

**Comment by gardlt** [comment]
is there any documents on what we would want on these guidelines? i think that adding .probot.js config would help this endeavor. https://github.com/bkeepers/PRobot

**Comment by wilkers-steve** [comment]
I agree with probot.  That's actually next on my list.  I've been playing around with a fork lately and trying to figure out exactly what functionality we're looking for.

**Comment by v1k0d3n** [comment]
probot is the way to go for labels being added automatically based on some matched items in issues/pr's. 

we still need guidelines and headings in each of the `Chart.yaml`, GUIDELINES and OWNERS to match what Kubernetes is doing in their repos.

**Comment by gardlt** [comment]
are there any templates on how we want the issues or PR to look.

**Comment by wilkers-steve** [comment]
The issue and PR templates have been merged in already. I should have the owners file in review here soon
