### ISSUE TITLE
fix: correct chart typos (globally)

### ISSUE THREAD

**Issue by intlabs** [att-comdev/openstack-helm#149]
In the common chart we have a function called: `joinListWithColon`
 * https://github.com/att-comdev/openstack-helm/blob/master/common/templates/_funcs.tpl#L1

This should be `joinListWithComma`

**Comment by v1k0d3n** [comment]
I'm going to tackle this issue @intlabs :+1:

**Comment by v1k0d3n** [comment]
this is a change across a few charts:

L33, L37, L41 - `openstack-helm/common/templates/snippets/_k8s_init_dep_check.tpl`
L3, L5, L8, L38  - `opensack-helm/neutron/templates/etc/_ml2-conf.ini.tpl`
L1 - `openstack-helm/common/templates/_funcs.tpl`
L18 - `openstack-helm/cinder/templates/etc/_cinder.conf.tpl`

I think those are all the ones that I could find.

**Comment by v1k0d3n** [comment]
this issue is resolved. thanks @alraddarla!
