### ISSUE TITLE
feat: maas chart values to include pluggable/optional secret creation

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#153]
@larryrensing i just noticed something about our MaaS chart. We want to ensure that MaaS users are able to generate (new) or use existing secret keys during MaaS initialization. this shouldn't be incredibly hard, but I definitely want to get this into the next release.

the change i'm looking for is here: https://github.com/att-comdev/dockerfiles/blob/master/maas/maas-region-controller/Dockerfile#L55

my recommendation is this:
create a custom init script and place into scripts
replace the CMD with your new script
generate random md5 and use as what gets > /var/lib/maas/secret
in the kubernetes manifest (chart) make this a conditional; if someone provides a secret include it. if they don't generate it and override this with a kubernetes-provided configmap.

**Comment by larryrensing** [comment]
it's not hardcoded in the dockerfile anymore-  i just haven't pushed my dockerfiles up to that repo yet, i've just been uploading the images to quay as i go

https://github.com/att-comdev/openstack-helm/blob/master/maas/templates/etc/_secret.tpl is where the current secret is being set.  one of my next steps is to make that configurable...  i tried doing a quick fix to make them both configurable via the values file but https://github.com/att-comdev/dockerfiles/blob/master/maas/maas-rack-controller/scripts/register-rack-controller.sh#L13 was giving me some issues. the region controller is capable of discovering the secret in /var/lib/maas/secret but the rack controller doesn't seem like it is aware that a secret can be mounted in that directory within the rack's container-- from what i saw, it needs to be fed the secret in the register command.  i'll just have to start the rack controller with a script and pull that out of the docker image 

it's on the list of things to do - i'll start working through this asap

**Comment by v1k0d3n** [comment]
ok..so push your changes, and update the MaaS charts as a first stop, I guess?

**Comment by v1k0d3n** [comment]
@larryrensing i think this is all done really. true?

**Comment by larryrensing** [comment]
With the current state of maas, users provide their own secret in values.yaml.  There isn't any secret generation performed if one isn't provided.

**Comment by v1k0d3n** [comment]
so let's do this: let's track the issue in [openstack-helm-adds](https://github.com/att-comdev/openstack-helm-addons). once MaaS and PostgreSQL are [merged](https://github.com/att-comdev/openstack-helm-addons/pull/4) into the repo, then we can complete work for [this pull request](https://github.com/att-comdev/openstack-helm-addons/issues/5) and track *the auto generation* of secrets in some other issue (and followup-PR). i'm going to close the issue here, since MaaS and PostgreSQL will be removed soon.
