### ISSUE TITLE
repo: add additional community docs to the openstack-helm repos

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#159]
**Kubernetes Version** (output of `kubectl version`): N/A

**Helm Client and Tiller Versions** (output of `helm version`): N/A

**Development or Deployment Environment?**: N/A

**Release Tag or Master**: N/A

**Expected Behavior**: N/A

**What Actually Happened**: N/A

**How to Reproduce the Issue** (as minimally as possible): N/A

**Any Additional Comments**: 
As we prepare our repo for the community, we need to address and include the following in our repository:

- changelog
- code of conduct
- contributing guidelines
- contributor agreements (?)
- expectations (for issues, pr's, contributors and reviewers)
- OWNERS
- RELEASES

**Comment by gardlt** [comment]
* OWNERS resolved in (#162)

**Comment by v1k0d3n** [comment]
@wilkers-steve none. closing.
