### ISSUE TITLE
docs:  add "helm repo add" to minikube.md TLDR

### ISSUE THREAD

**Issue by mattmceuen** [att-comdev/openstack-helm#172]
**Is this a bug report or feature request?** (choose one):
Bug Report (documentation)

**Kubernetes Version** (output of `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Helm Client and Tiller Versions** (output of `helm version`):
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}

**Development or Deployment Environment?**:
Development

**Release Tag or Master**:
Master

**Expected Behavior**:
"make" works

**What Actually Happened**:
"make" returns:
Error: no repository definition for http://localhost:8879/charts. Try 'helm repo add'

**How to Reproduce the Issue** (as minimally as possible):
Follow the TLDR; instructions in minikube.md

**Any Additional Comments**:
The detailed "Getting Started" guide includes "helm repo add local http://localhost:8879/charts", but the TLDR summary leaves it out.  Just need to add that line to the TLDR.

**Comment by v1k0d3n** [comment]
you know...i just realized that yesterday too. good catch @mattmceuen...this is a welcome PR!

**Comment by mattmceuen** [comment]
on it :)
