### ISSUE TITLE
ci: Get `helm install local/foo` running in TravisCI

### ISSUE THREAD

**Issue by wilkers-steve** [att-comdev/openstack-helm#183]
**Is this a bug report or feature request?** (choose one):  Feature request

I'd like to explore the possibility of running `helm install local/foo` in the TravisCI jobs so we can verify charts are being installed properly.  I see this happening in one of two approaches:  we either try to run these charts inside TravisCI (resource intensive, likely) or we leverage the locally running Tiller and stand up an external Kubernetes cluster to serve as a playground for these charts to install to -- an AIO kubeadm node with sufficient resources could suffice here.  And of course we'd run this against both developer and deployment workflows.

**Kubernetes Version** (output of `kubectl version`): N/A

**Helm Client and Tiller Versions** (output of `helm version`): N/A

**Development or Deployment Environment?**: Both

**Release Tag or Master**:

**Expected Behavior**:

**What Actually Happened**:

**How to Reproduce the Issue** (as minimally as possible):

**Any Additional Comments**:  I've started work on this.  If you'd like to assign it to me, I don't anticipate this taking very long.

**Comment by v1k0d3n** [comment]
you already got the issue. thanks @wilkers-steve

**Comment by janwillies** [comment]
The next helm release (due next week if everything goes well) will feature a [testing framework](https://github.com/kubernetes/helm/issues/1163#issuecomment-271875395). This could be leveraged for verifying an expected output.

**Comment by wilkers-steve** [comment]
Thanks for the heads up Jan. This is certainly something to look into using and even contribute to directly if it's something we can leverage.

**Comment by wilkers-steve** [comment]
@v1k0d3n I'm closing this issue since it's not necessary moving forward.
