### ISSUE TITLE
feat: Implement HA postgresql

### ISSUE THREAD

**Issue by larryrensing** [att-comdev/openstack-helm#186]
**Is this a bug report or feature request?** (choose one):
Feature request

We need to have a HA, resilient postgresql cluster.  Currently, MaaS is the only project we are using postgresql with, and the postgresql instance is running internal to the container.  Future projects may need to leverage postgresql.

**Kubernetes Version** (output of `kubectl version`):

n/a

**Helm Client and Tiller Versions** (output of `helm version`):

n/a

**Development or Deployment Environment?**:

n/a

**Release Tag or Master**:

TBD

**Expected Behavior**:

n/a

**What Actually Happened**:
n/a

**How to Reproduce the Issue** (as minimally as possible):
n/a
**Any Additional Comments**:

https://github.com/att-comdev/openstack-helm/pull/154 Current PR in flight supports a single node postgresql cluster.  This is fine for MaaS, as it is the only project that uses postgresql, but future projects in this repository may need a HA postgresql solution.

**Comment by janwillies** [comment]
one possible option would be via patroni: https://github.com/zalando/patroni

**Comment by renmak** [comment]
Another option would be via Stolon: https://github.com/sorintlab/stolon

**Comment by v1k0d3n** [comment]
FYI: we need to move this discussion to [openstack-helm-addons](https://github.com/att-comdev/openstack-helm-addons) going forward.

**Comment by masterdubs** [comment]
Maybe we can use this : https://github.com/lwolf/stolon-chart/tree/master/stolon

**Comment by v1k0d3n** [comment]
new issue created in [openstack-helm-addons #7](https://github.com/att-comdev/openstack-helm-addons/issues/7)
