### ISSUE TITLE
feat: add basic ironic chart

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#191]
**Kubernetes Version** (output of `kubectl version`):  N/A

**Helm Client and Tiller Versions** (output of `helm version`):  N/A

**Development or Deployment Environment?**:  N/A

**Release Tag or Master**:  N/A

**Expected Behavior**:  N/A

**What Actually Happened**:  N/A

**How to Reproduce the Issue** (as minimally as possible):  N/A

**Any Additional Comments**:  
another chart that we would like to deliver is a basic ironic chart. the ironic chart can start much like the other openstack-helm charts started, with a goal of improving them over time.

**Comment by v1k0d3n** [comment]
@maris-accenture this one is for you! :-)

**Comment by maris-accenture** [comment]
@v1k0d3n Thanks!

**Comment by ss7pro** [comment]
If would first start with design document :) We at Intel been doing Ironic @ Kubernetes for quite a long time and would really like to share our experience around design and taking advantage of multiple recenty added features.

**Comment by v1k0d3n** [comment]
@ss7pro fair point. some of this is currently being framed up in our docs. these are in-flight, and it would be nice to have your feedback from Intel (since your team has a lot of experience with this).

[General Project Philosophy](https://github.com/att-comdev/openstack-helm/blob/master/docs/helm_overrides.md)

**Comment by v1k0d3n** [comment]
@ss7pro i am preparing a list of items to discuss at the PTG as we start to have the community drive the project, and as we attempt to find a final home for openstack-helm. is your team going to be at the PTG? i will be publishing a list of items soon (i'd like to get them out today), and then we'll have the community formalize a roadmap for the project going forward.

**Comment by ss7pro** [comment]
We wont't make it to the PTG but we're more than happy to review this list :)

**Comment by v1k0d3n** [comment]
closed out the PR and will reopen when we're in openstack proper. closing issue.
