### ISSUE TITLE
bug: Stackenetes Entrpoint Image (v0.1.0) does not correctly detect service dependencies with k8s >1.5

### ISSUE THREAD

**Issue by intlabs** [att-comdev/openstack-helm#195]
**Is this a bug report or feature request?** (choose one):

**Kubernetes Version** (output of `kubectl version`): >=v1.5.0

**Helm Client and Tiller Versions** (output of `helm version`): N/A

**Development or Deployment Environment?**: N/A

**Release Tag or Master**: N/A

**Expected Behavior**: For entry-point image to correctly detect service status

**What Actually Happened**: Image incorrectly resolves services as available when they are not.

**How to Reproduce the Issue** (as minimally as possible):
Use v0.1.0 image with k8s >v1.5.0

**Any Additional Comments**:
This can be simply resolved by updating our charts to use v0.1.1 of the `kubernetes-entrypoint` image.

eg: https://github.com/att-comdev/openstack-helm/blob/master/glance/values.yaml#L24
this:
``` yaml
dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.1.0
```
should become:
``` yaml
dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.1.1
```
this will need changed in every ```values.yaml``` file that uses the `kubernetes-entrypoint` image.

**Comment by alanmeadows** [comment]
Are we sure this is the _totality_ of the issue (at least in K8s 1.5.1)? @larryrensing has seen a service object add endpoints that were not yet in a ready state (and allow non-ready service endpoints was not annotated, whatever that annotation is -- on the service).  He's seen this simply using kubectl describe. I believe that would break anything trying to do service type validations.  I am wondering what does 0.1.1 do to address that?

**Comment by ss7pro** [comment]
@alanmeadows This bug: https://github.com/stackanetes/kubernetes-entrypoint/pull/21/files#diff-96a47b800d818cc653a127693efd308b 

kubernetes-entrypoint was just waiting until any endpoint will appear in the service when we should wait for only ready ones. Patch above fixes that issue.

**Comment by DTadrzak** [comment]
We need to bump version to 0.1.1

**Comment by intlabs** [comment]
@alanmeadows this will definatly go some way to resolving the issue as @ss7pro has explained much better than I have (should have linked in the original issue...). But I've also seen similar 'phantom' endpoints on occasion which this would not resolve.

**Comment by alanmeadows** [comment]
If entrypoint actually examines the _readiness_ of the endpoints in the service list, as opposed to just their mere existence, this may mask the K8s phantom issue then.  I wasn't aware it was going to that length.  0.1.1 seems like a good move then.
