### ISSUE TITLE
feat: Kubernetes Logging Monitoring and Alerting Building Blocks

### ISSUE THREAD

**Issue by andrecolin** [att-comdev/openstack-helm#202]
There will be many solutions to monitoring Kubernetes and the Applications running on Kubernetes. This issue request is to identify the components that can easily be combined into a Deployment Helm Chart and use these building blocks to form several best of breads Logging Monitoring and Alerting (LMA) Solution.  
We need the following building blocks Helm Charts making sure they are idempotent and can be combined with any of the other Charts to form a complete LMA Solution. Some on the list may already have Charts, we just need to make sure it is in the correct format we desire. Part I will be to Helm Chartify the components and part 2 will be to configure sample deployment charts to make a solution

ElasticSearch
Kibana
Heapster
Grafana
InfluxDB
FluentD
Prometheus
OpenTDB
SNAP

**Comment by v1k0d3n** [comment]
@andrecolin you mentioned having charts for each of these items. do these work provide good starters? i would imagine that many of these items we want to really be upstream in other sources (when possible):

ElasticSearch: [kubernetes/charts/incubator/elasticsearch](https://github.com/kubernetes/charts/tree/master/incubator/elasticsearch), or there are 3 versions of elasticsearch in [fabric8io's repo](https://github.com/fabric8io/charts). there is also [Samsung's k2 Charts](https://github.com/samsung-cnct/k2-charts) that contain's an elasticsearch chart.
Kibana: Same links above have Kibana versions.
Heapster: [Samsung k2](https://github.com/samsung-cnct/k2-charts) has heapster
Grafana: Grafana is in all of them.
InfluxDB: [Kubernetes](https://github.com/kubernetes/charts/tree/master/stable)
FluentD: [Fabric8](https://github.com/fabric8io/charts) has a FluentD chart to use
Prometheus: [Fabric8](https://github.com/fabric8io/charts) has 2 versions, [Samsung k2](https://github.com/samsung-cnct/k2-charts) has one, and [Kubernetes Charts](https://github.com/kubernetes/charts/tree/master/stable) has one.
OpenTDB: New Item
SNAP: New Item

**Comment by v1k0d3n** [comment]
moved to openstack-helm-addons repo [issue 1](https://github.com/att-comdev/openstack-helm-addons/issues/1).
