### ISSUE TITLE
misc: move non-openstack-helm items out of this repo and into infra and addons

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#209]
I believe it's time to start taking non-openstack-helm related items out of this repo, and place them into other more appropriate repositories:

**openstack-helm-infra:**
- ceph
- ingress
- mariadb
- memcached
- postgres
- rabbitmq

**openstack-helm-addons:**
- maas
- clair (security scanner)
- grafana
- kibana
- prometheus

this is a planning effort. need input from @alanmeadows

**Comment by alanmeadows** [comment]
Completely agreed with the layout proposed.

I think we should define infra as "foundational infrastructure elements that are necessary to power OpenStack" and of course, there could be elements there that may compete amongst one another, for instance, ceph and glusterfs, or mariadb and postgre.

I think we describe addons as things that embelish OpenStack and are not necessary to operate it.

This will of course alter our docs on how one deploys, as you will need to _at least_ fetch both infra and openstack-helm native to build a stack.  This is where something like Armada could help if we put together a stack-up.yaml.

**Comment by wilkers-steve** [comment]
I agree as well, and I like @alanmeadows's definitions of infra and add-ons.

**Comment by v1k0d3n** [comment]
@alanmeadows a potential thought to consider would be to use a submodule for infra items, as then it would be very easy to include these as just one additional step. this could be done by leveraging CI out of the box too, but some thought/care has to be considered on where this repo ends up (gerrit/openstack projects will not handle submodules well, while github/CNCF would be fine). then it's all about messaging and handling dependencies.

**Comment by intlabs** [comment]
The suggestions from @alanmeadows are pretty close to the ideal layout I'd like to see at some point. Though as @v1k0d3n's pointed out the logistics of the repo's we maintain may be driven by the project's eventual home.

**Comment by alanmeadows** [comment]
Agreed, the logistics of how the repositories interrelate and whether openstack-helm itself can reference them in a meaningful way beyond documentation links is entirely dependent on a home - it seems locking this in first (at least the destination, not the actual move) makes sense before the effort of migration then.

Just one comment--git submodules certainly provide a powerful way for us to interlink repositories if that becomes an option.  In fact, other then documentation references, or a monolithic "root directory partitioned" repository, that is likely the _only_ way.  That said though, my experience with them, including both using and managing them for a project has been far from positive.

**Comment by alanmeadows** [comment]
@DTadrzak @ss7pro please feel free to add any additional thoughts!

**Comment by ss7pro** [comment]
+1 except submodules as we have very bad expirience with that when multiple people are sending pull requests changing reference to sub modules (permament need for rebasing reference to a submodule).

**Comment by v1k0d3n** [comment]
@ss7pro good advice. and I +1 other's comments as well. i think a potential improvement is using `subtree` over `submodule`, in which things become easier to maintain.

**Comment by larryrensing** [comment]
Agree with @alanmeadows. "Infra" for db backends and the projects needed to stand up your deployment, "addons" for ancillary OpenStack projects.

**Comment by v1k0d3n** [comment]
looking over this a bit more this evening, it's becoming pretty clear that pulling MaaS and Postgres out of the repo requires much deeper thought/discussion. both, but especially MaaS are married to helm-toolkit. i'm not sure that this should really be the approach. it's really just a different way to handle dependencies, but our way carries more debt. aren't we trying to release debt by eventually getting these up to kubernetes/charts? how would we do this with this tight coupling? i think in order for these charts to be useful outside of the Openstack-Helm repo, we need to refactor them removing the Helm-Toolkit references.

**Comment by intlabs** [comment]
@v1k0d3n That works for me, though itself comes with debt, in a classic tradeoff:
 - helm-toolkit removes the debt of having to maintain a common set of functions across multiple charts and ensures consistency, but means we need to carry it about.
 - a `_helpers.tpl` in each chart removes the debt of having to carry that dep around, but re-introduces the burden of having to maintain functions and style consistency across our repo landscape.

I'd need to have a proper look but Maas appears to not be using the helm-toolkit that heavily:
 - `helm-toolkit.postgresql_host` is in a few manifests
 - `helm-toolkit.kubernetes_entrypoint_init_container` is used in the import job
 - `helm-toolkit.template` is used in the bin and config configMaps

Based on this I wonder if an appropriate way to continue would be to place these functions verbatim into a `_helpers.tpl`? If we were using many more than (and picking an arbitrary number) say 6 functions from the toolkit in a chart, then we may have issues with the scalability of this approach, but it seems fine to me here.

**Comment by v1k0d3n** [comment]
@intlabs yup i agree with that. it really depends on what we see with the future of MaaS and how deep this will go (on the AT&T side, quite a bit). but that also may make it a *questionable* candidate for kubernetes/charts (i would imagine) if it continues down the `helm-toolkit` path. i'm just thinking out loud here...

**Comment by v1k0d3n** [comment]
maas and postgresql have been moved out of the repo, and are in openstack-helm-addons. issues have been created to covert to a `_helpers.tpl` for maas and postgresql in that repo. i think the move of ceph, rabbit, memcached really needs to be discussed in more depth, as i would personally prefer to keep these with the other charts as we head towards openstack proper so that the project is "complete" as is. later  in time,  if/when we have other repos, like `openstack-helm-infra` or `openstack-helm-addons` in openstack, we can discuss this further, but as the repos will [at this immediate point] span between openstack and att-comdev, i would rather keep core components together.
