### ISSUE TITLE
Token generation process for AIC-Helm

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#21]
We may be able to handle secretes like this in the near future:  https://github.com/andrewstuart/helm/blob/5d58b7792c4b0b56ec8eee49cfcc79980e9b0ed3/docs/chart_template_guide/accessing_files.md#secrets

**Comment by alanmeadows** [comment]
This worked fine but presented problems with nested templates.  In other words, if we try to do this in common it will fail as it does not see .Files from the context of common, but rather the including chart.  This works fine if you do not leverage the portion of the chart which relies on .Files within any other chart.

**Comment by v1k0d3n** [comment]
captured in issue  #32. closing this, since part of this was completed in 0.1.0.
