### ISSUE TITLE
ci: gating based on +2 model

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#214]
@wilkers-steve we need to start gating on a successful CI build, followed by a +2 approach in GitHub. let's start making this happen, and when our CI is improved (potentially today, i'm hoping?) we can start looking for additional project core reviewers at the PTG.

**Comment by v1k0d3n** [comment]
@nadeemanwar my hope is that we would start documenting CI aspects very soon as well. if we can get improvements in before the PTG, that would be extremely helpful. then we can start working on CI documentation and developer expectations based on what is currently in place (this will be helpful for devs to know what to look for in gating and CI).

**Comment by intlabs** [comment]
@v1k0d3n this would be awesome! If we could eventually get to a 2*+2 model that would be the ideal from my PoV.

**Comment by v1k0d3n** [comment]
@intlabs that works. i mean really...i want the community to start driving the project. that means these things all need to be in order, published, voted and decided on publicly, and maintained by the community. i will also be looking for additional cores at the PTG and beyond. we're actively starting this process now.

**Comment by wilkers-steve** [comment]
@v1k0d3n We can probably close this issue out since we're looking at OpenStack-Infra.  This should be handled on their end once we're merged in.  At that point, we'll just be responsible for the jobs and not the gating.

**Comment by v1k0d3n** [comment]
yup. closing.
