### ISSUE TITLE
bug: Missing template for nova configmaps

### ISSUE THREAD

**Issue by wilkers-steve** [att-comdev/openstack-helm#230]
**Is this a bug report or feature request?** (choose one): Bug report

**Kubernetes Version** (output of `kubectl version`): N/A

**Helm Client and Tiller Versions** (output of `helm version`): N/A

**Development or Deployment Environment?**: N/A

**Release Tag or Master**: Master

**Expected Behavior**: Nova chart lints and installs with `--dry-run` successfully

**What Actually Happened**:  Error reported during `helm install --dry-run` due to missing template

**How to Reproduce the Issue** (as minimally as possible):  Run `helm install nova --dry-run --debug`

**Any Additional Comments**:

This issue is raised because of the template declared in the nova etc configmap found here: https://github.com/att-comdev/openstack-helm/blob/master/nova/templates/configmap-etc.yaml#L22.  We can look in the /etc directory in nova and see there's a template for _ceph.conf.tpl.  I'm assuming this was just a misnaming here.

**Comment by gardlt** [comment]
it seem both _ceph.conf.tpl and _ceph.client.cinder.keyring.yaml.tpl are needed. we might be missing a tpl or having a bad import.

**Comment by intlabs** [comment]
@wilkers-steve, @gardlt I think I need to that the hold my hands up to this one, looks like I butchered this as part of my cleanup work. See here, for the lines I accidently removed: https://github.com/att-comdev/openstack-helm/blob/8afa729ffba9378b76e63dfc282f16ecf1d9baa9/nova/templates/configmap-etc.yaml#L7-L8.
I'll put a fix in asap.
