### ISSUE TITLE
Copyright headers break rabbitmq

### ISSUE THREAD

**Issue by mattmceuen** [att-comdev/openstack-helm#237]
**Is this a bug report or feature request?** (choose one):
Bug report

**Kubernetes Version** (output of `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Helm Client and Tiller Versions** (output of `helm version`):
Client: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.1.3", GitCommit:"5cbc48fb305ca4bf68c26eb8d2a7eb363227e973", GitTreeState:"clean"}

**Development or Deployment Environment?**:
Single bare metal node - dev

**Release Tag or Master**:
Master

**Expected Behavior**:
rabbitmq starts

**What Actually Happened**:
rabbitmq errors

**How to Reproduce the Issue** (as minimally as possible):
Deploy rabbitmq with the current codebase

**Any Additional Comments**:
The erlang template files break rabbitmq startup when they include the new #-comment style copyright header.  Removing the copyright headers resolves the issue.

These are the error messages that get generated:
erlang.cookie:  Bad characters in cookie
rabbitmq.config:  error in config file \"/etc/rabbitmq/rabbitmq.config\" (1): syntax error before: Copyright
enabled_plugins:  cannot_read_enabled_plugins_file,"/etc/rabbitmq/enabled_plugins" ..."syntax error before: ",["Copyright"]

**Comment by mattmceuen** [comment]
Looks like erlang-style %-comments work for rabbitmq.config and enabled_plugins, although it appears we may need to leave the copyright off of erlang.cookie.  If that seems like a good resolution I can make the change.

**Comment by jallirs** [comment]
Seems fine :) I would say go ahead :)

**Comment by mattmceuen** [comment]
Thanks Randeep! :) PR submitted.

**Comment by v1k0d3n** [comment]
good catch @mattmceuen. PR approved (LGTM).
