### ISSUE TITLE
MaaS error when reading secret

### ISSUE THREAD

**Issue by larryrensing** [att-comdev/openstack-helm#241]
**Is this a bug report or feature request?** (choose one):
bug report

MaaS relies on a shared secret between the rack and region controllers to authenticate.  Every time the secret file is read, the following error occurs: 

`binascii.Error: Non-hexadecimal digit found`

MaaS does not appear to be able to parse comments out from the apache headers we are putting in the _secret.tpl file, so those apache headers need to be removed.

**Kubernetes Version** (output of `kubectl version`):
any
**Helm Client and Tiller Versions** (output of `helm version`):
any
**Development or Deployment Environment?**:
both
**Release Tag or Master**:
master
**Expected Behavior**:
MaaS reads secret file without any hiccups
**What Actually Happened**:
MaaS can't parse apache headers and throws exceptions
**How to Reproduce the Issue** (as minimally as possible):
n/a
**Any Additional Comments**:

**Comment by v1k0d3n** [comment]
issue merged. thanks @larryrensing!
