### ISSUE TITLE
mariadb chart fails with kolla/centos-binary-mariadb image

### ISSUE THREAD

**Issue by wilreichert** [att-comdev/openstack-helm#243]
**Is this a bug report or feature request?** (choose one):
bug 

**Kubernetes Version** (output of `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Helm Client and Tiller Versions** (output of `helm version`):
Client: &version.Version{SemVer:"v2.2.1", GitCommit:"db531fd75fb2a1fb0841a98d9e55c58c21f70f4c", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.1", GitCommit:"db531fd75fb2a1fb0841a98d9e55c58c21f70f4c", GitTreeState:"clean"}

**Development or Deployment Environment?**:
deployment 3 node cluster w/ ceph 

**Release Tag or Master**:
master

Steps to reproduce:
```
% git clone clone https://github.com/att-comdev/openstack-helm
<<<cut>>>
% cd openstack-helm
% helm install mariadb --set images.mariadb="kolla/centos-binary-mariadb:master" --set volume.class_name=ceph --namespace test --name testdb
<<<cut>>>
<<<wait a couple minutes >>>
% kubectl get po -n test
NAME                 READY     STATUS              RESTARTS   AGE
mariadb-0            0/1       Pending             0          1m
mariadb-seed-7mqq8   0/1       ContainerCreating   0          2s
% kubectl logs mariadb-seed-7mqq8 -n test
INFO:__main__:Loading config file at /var/lib/kolla/config_files/config.json
ERROR:__main__:Unexpected error:
Traceback (most recent call last):
  File "/usr/local/bin/kolla_set_configs", line 412, in <module>
    main()
  File "/usr/local/bin/kolla_set_configs", line 401, in main
    config = load_config()
  File "/usr/local/bin/kolla_set_configs", line 316, in load_config
    config = load_from_file()
  File "/usr/local/bin/kolla_set_configs", line 304, in load_from_file
    with open(config_file) as f:
IOError: [Errno 2] No such file or directory: '/var/lib/kolla/config_files/config.json'
% helm status testdb
LAST DEPLOYED: Fri Mar  3 11:27:29 2017
NAMESPACE: test
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME         DATA  AGE
mariadb-bin  5     17m
mariadb-etc  8     17m

==> v1/Service
NAME     CLUSTER-IP      EXTERNAL-IP  PORT(S)   AGE
mariadb  10.100.167.181  <none>       3306/TCP  17m

==> batch/v1/Job
NAME          DESIRED  SUCCESSFUL  AGE
mariadb-seed  1        0           17m

==> apps/v1beta1/StatefulSet
NAME     DESIRED  CURRENT  AGE
mariadb  3        1        17m
```

And it gets stuck.

kolla defines a CMD [here](https://github.com/openstack/kolla/blob/master/docker/base/Dockerfile.j2#L333 )
and most of the other charts override it via a 'command:' in the chart yaml. 

mariadb uses a COMMAND env variable which apparently doesn't get precedence.

```
% grep -r -n COMMAND *
helm-toolkit/templates/snippets/_k8s_init_dep_check.tpl:66:      "name": "COMMAND",
mariadb/templates/deployment.yaml:84:            - name: COMMAND
mariadb/templates/job-seed.yaml:57:            - name: COMMAND
```

**Comment by v1k0d3n** [comment]
resolved in #244
