### ISSUE TITLE
bug: Incorrect hosts used for Memcached in Horizon and Keystone

### ISSUE THREAD

**Issue by intlabs** [att-comdev/openstack-helm#255]
**Is this a bug report or feature request?** (choose one): Bug

**Kubernetes Version**: N/A

**Helm Client and Tiller Versions**: N/A

**Development or Deployment Environment?**: N/A

**Release Tag or Master**: Master

**Expected Behavior**:
For Horizon and Keystone to use the correct value for Memcached in config files.
**What Actually Happened**:
Both Horizon and Keystone use the RabbitMQ hostname instead.
**Any Additional Comments**:
See:
 - https://github.com/att-comdev/openstack-helm/blame/master/horizon/templates/etc/_local_settings.tpl#L147
 - https://github.com/att-comdev/openstack-helm/blame/master/keystone/templates/etc/_keystone.conf.tpl#L25
 - https://github.com/att-comdev/openstack-helm/blame/master/keystone/templates/etc/_keystone.conf.tpl#L32

**Comment by larryrensing** [comment]
fixing this @v1k0d3n

**Comment by intlabs** [comment]
@larryrensing thanks dude :)
