### ISSUE TITLE
feat: Chart to deploy Ceilometer

### ISSUE THREAD

**Issue by larryrensing** [att-comdev/openstack-helm#263]
**Is this a bug report or feature request?** (choose one):

Feature

**Kubernetes Version** (output of `kubectl version`):
n/a

**Helm Client and Tiller Versions** (output of `helm version`):
n/a

**Development or Deployment Environment?**:
n/a

**Release Tag or Master**:
master

**Any additional comments**
We would like to deliver a helm chart to deploy ceilometer

**Comment by v1k0d3n** [comment]
@larryrensing, i'm assuming this is an 0.4.0 release,  or are you attempting to get in for 0.3.0?

**Comment by wilkers-steve** [comment]
@larryrensing Going to close this out, since we'll be in OpenStack before 0.4.0.  We can open up a blueprint and track it once we make our move.
