### ISSUE TITLE
bug: Default node port value in Horizon values.yaml invalid

### ISSUE THREAD

**Issue by wilkers-steve** [att-comdev/openstack-helm#277]
**Is this a bug report or feature request?** (choose one): Bug

**Kubernetes Version** (output of `kubectl version`): v1.5.1

**Helm Client and Tiller Versions** (output of `helm version`): 2.2.2

**Development or Deployment Environment?**: Development

**Release Tag or Master**: Master

**Expected Behavior**: Enable node port in horizon's values.yaml and access horizon

**What Actually Happened**:  Accessed the Kubernetes dashboard instead.

**How to Reproduce the Issue** (as minimally as possible):  set `enable_node_port` to true in Horizon's values.yaml and use the default node port value:  https://github.com/att-comdev/openstack-helm/blob/master/horizon/values.yaml#L40

**Any Additional Comments**:

The default value for Horizon's node port conflicts with the kubernetes-dashboard service's node port.  We should document the default values set for node ports.

Can be addressed as part of: #257 if necessary

**Comment by v1k0d3n** [comment]
merged #279. resolved.

**Comment by wilkers-steve** [comment]
This issues unrelated to #279, but still a quick enough fix.  We could have @larryrensing tackle it as part of his broader node port changes

**Comment by v1k0d3n** [comment]
sorry @wilkers-steve i was looking at another issue and accidentally closed this one (#278/#279). reopened.

**Comment by wilkers-steve** [comment]
@v1k0d3n no worries. it happens :)
