### ISSUE TITLE
bug: "OPENSTACK_KEYSTONE_URL =" missing from horizon configuration hence not able to login to horizon with keystone credentials.

### ISSUE THREAD

**Issue by krrypto** [att-comdev/openstack-helm#299]
**Is this a bug report or feature request?** (choose one):
bug

**Kubernetes Version** (output of `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:34:32Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
**Helm Client and Tiller Versions** (output of `helm version`):
helm version
Client: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.2.2", GitCommit:"1b330722aafcb8123114ae51f69d1e884a326f3e", GitTreeState:"clean"}
**Development or Deployment Environment?**:
Deployment

**Expected Behavior**:
Should be able to log into horizon with admin credentials

**What Actually Happened**:
not able to login to horizon and  horizon logs showing not able to log in admin user.
after adding 
**OPENSTACK_KEYSTONE_URL ="http://keystone-api.openstack:5000/v3"** 
in /etc/openstack-dashboard/local_settings horizon started accepting default username and password.
before it was empty **OPENSTACK_KEYSTONE_URL =""**
**How to Reproduce the Issue** (as minimally as possible):
standard deployment with out editing any values.yaml file
**Any Additional Comments**:
Not sure if its environment specific ,deleted and re created pods many times but still above parameter was missing.Openstack commands are working with admin credentials but only horizon was not working.

**Comment by intlabs** [comment]
I cannot reproduce this with the current `master`, ( https://paste.fedoraproject.org/paste/ot668lx4Pqbh6zrOHuy9PF5M1UNdIGYhyRLivL9gydE=/raw ) could someone else confirm this?

**Comment by krrypto** [comment]
issue affects committ 3e62cd54e2751afa7cfd2cf0a2ae910e43e25385 and is working on latest committ
