### ISSUE TITLE
bug: Unable to pull image for rabbitmq

### ISSUE THREAD

**Issue by wilkers-steve** [att-comdev/openstack-helm#306]
**Is this a bug report or feature request?** (choose one): bug

**Kubernetes Version** (output of `kubectl version`): 1.5.2

**Helm Client and Tiller Versions** (output of `helm version`): 2.2.3

**Development or Deployment Environment?**: Development

**Release Tag or Master**: Master

**Expected Behavior**: Running `helm install --name=rabbitmq local/rabbitmq --namespace=rabbitmq` should result in a successful release 

**What Actually Happened**:  Pod fails to start with an ImagePullBackOff.  Appears to be due to an invalid rabbitmq image tag

**How to Reproduce the Issue** (as minimally as possible): Follow standard development flow up to installing rabbitmq

**Any Additional Comments**:

Log output: 
29s		15s		2	{kubelet ip-172-31-8-127}					Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "rabbitmq" with ErrImagePull: "image pull failed for registry.mcp.fuel-infra.org/mcp/rabbitmq:ocata-unstable, this may be because there are no credentials on this request.  details: (Error: image mcp/rabbitmq:ocata-unstable not found)"

This should tie in to issue #246.

**Comment by intlabs** [comment]
Confirmed, it appears that the entire MCP registry has either moved or been removed.

**Comment by intlabs** [comment]
I have published an image at: `docker.io/port/fuel-mcp-rabbitmq:ocata-unstable` that we can use as a workaround until this is resolved.

**Comment by wilkers-steve** [comment]
Thanks @intlabs
