### ISSUE TITLE
bug: fix links in docs

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#323]
some of the documentation links are broken. i am going to work on fixing these today.

**Comment by renmak** [comment]
Brandon,
As i mentioned in Slack, here are few other issues that i found. 

1) In guide, we are suggesting to use latest Minikube version (in my case v0.17.1). With this version of Minikube, i was not able to use Kubernetes v1.5.1.
I ended up using v1.5.3

2) Also in guide, we have following instruction

# Get a list of the current tags:
git tag -l

# Checkout the tag you want to work with (use master for development):
# For stability and testing, checkout the latest stable branch.
git checkout 0.2.0

I don't think we have tag 0.2.0 in github for our project.
