### ISSUE TITLE
Nova installation fails with "invalid character 'e' in literal true (expecting 'r')"

### ISSUE THREAD

**Issue by dulek** [att-comdev/openstack-helm#324]
**Kubernetes Version** (output of `kubectl version`):
1.5.3

**Helm Client and Tiller Versions** (output of `helm version`):
2.2.3

**Development or Deployment Environment?**:
Devel

**Release Tag or Master**:
master

**Expected Behavior**:
Nova chart installs without problems.

**What Actually Happened**:
```mdulko:openstack-helm/ (master) $ helm install --name=nova local/nova --set control_replicas=1 --namespace=openstack --debug              
Created tunnel using local port: '39433'
SERVER: "localhost:39433"
Fetched local/nova to nova-0.1.0.tgz
CHART PATH: /home/mdulko/openstack/openstack-helm/nova-0.1.0.tgz
Error: release nova failed: Job in version "v1" cannot be handled as a Job: invalid character 'e' in literal true (expecting 'r')
```

**How to Reproduce the Issue** (as minimally as possible):
On current master try to deploy Nova using:
```
helm install --name=nova local/nova --set control_replicas=1 --namespace=openstack
```

**Any Additional Comments**:

**Comment by v1k0d3n** [comment]
fixed in #325. thanks for the PR @dulek
