### ISSUE TITLE
Convert ceph monitors to a statefulset

### ISSUE THREAD

**Issue by alanmeadows** [att-comdev/openstack-helm#61]
The ceph monitors require reliable IP addressing, they should be converted to a statefulset.

**Comment by alanmeadows** [comment]
@intlabs Pete, since you may have been playing with this chart, we want to change the monitors over to a statefulset, and also, the ceph osd containers do not restart properly, on restart they crash with an auth error.  Have you hit or overcome this? I know you are working with Sebestian on an upstream chart as well but likely this is forthcoming some time in the future?

**Comment by intlabs** [comment]
@alanmeadows, as we discussed yesterday I've moved the monitors over to statefulset in the work I've been doing to address this exact issue. My initial tests have not shown the same results as you from simply killing the container running the OSD, however, I'll test properly today and report my findings back.

**Comment by alanmeadows** [comment]
Resolved with https://github.com/att-comdev/openstack-helm/pull/83
