### ISSUE TITLE
helm: add resource quotas for each of the charts and default values

### ISSUE THREAD

**Issue by v1k0d3n** [att-comdev/openstack-helm#64]
each of the openstack-helm charts need to have configurable resource quotas: i.e. `chart/templates//deployment.yaml` & `chart/values.yaml`

for more information: http://kubernetes.io/docs/admin/resourcequota/

**Comment by intlabs** [comment]
For development purposes, these should be disabled using the same method that the MariaDB chart uses: https://github.com/att-comdev/openstack-helm/blob/master/mariadb/values.yaml#L10-L21.

**Comment by DTadrzak** [comment]
I agree with @intlabs

**Comment by v1k0d3n** [comment]
This issue has been addressed with the merge of #103
