### ISSUE TITLE
feat/docs: Default values for development do not work on Atomic Linux

### ISSUE THREAD

**Issue by intlabs** [att-comdev/openstack-helm#95]
Many mount points including `/` are read-only on RPM-OSTREE Linux distros like Atomic, as a result, the default development values do not work: as there is no `/data` directory.

We should either update the documentation to tell users how to change this value, or update it to one that is acceptable for both minikube and Atomic Linux e.g: `/var/lib/localkube`.

* https://github.com/att-comdev/openstack-helm/blob/master/mariadb/values.yaml#L22

**Comment by v1k0d3n** [comment]
fixed as part of #296.
